project_id = "hdbzpunncyxgzilzmskj"

[functions.send-contact-email]
verify_jwt = false

[functions.send-brevo-email]
verify_jwt = false

[functions.validate-admin-pin]
verify_jwt = false

[functions.submit_lead]
verify_jwt = false